function json(d){return new Response(JSON.stringify(d),{headers:{"Content-Type":"application/json","Access-Control-Allow-Origin":"*"}});}
async function ghFetch(env,ep){if(!env.GITHUB_TOKEN)return null;try{const r=await fetch(`https://api.github.com${ep}`,{headers:{"Authorization":`Bearer ${env.GITHUB_TOKEN}`,"Accept":"application/vnd.github+json","User-Agent":"BlackRoad-OS-Worker/2.0"}});return r.ok?r.json():null;}catch{return null;}}
const POSTS=[{title:"Building 30,000 AI Agents on Raspberry Pi",date:"2026-02-20",tags:["ai","hardware","agents"],desc:"How we distribute 30,000 concurrent AI agents across a Pi fleet using a Cloudflare tunnel, Ollama, and our tokenless gateway architecture."},{title:"PS-SHA∞: Hash-Chained Memory for AI Systems",date:"2026-02-15",tags:["memory","ai","architecture"],desc:"Designing tamper-evident persistent memory for AI agents using hash-chain journals and the trinary logic epistemic system."},{title:"The Tokenless Gateway Pattern",date:"2026-02-10",tags:["security","architecture","agents"],desc:"Why we moved all API keys out of agent code and into a gateway — and how it changed everything about our security model."},{title:"CECE: Portable AI Identity Across Providers",date:"2026-02-05",tags:["identity","ai","cece"],desc:"Building an AI identity that persists across Claude, GPT, Ollama, and any future model — your agents own their own identity."},{title:"37 CLI Tools in One Binary: The BR Architecture",date:"2026-01-28",tags:["cli","architecture","devops"],desc:"How we built a modular CLI with 37 independent tools that self-initialize, share SQLite state, and compose naturally."}];
export default {
  async fetch(req,env){
    const {pathname:p}=new URL(req.url);
    if(p==="/health") return json({status:"ok"});
    if(p==="/api/posts") return json({total:POSTS.length,posts:POSTS});
    const releases=await ghFetch(env,"/repos/BlackRoad-OS-Inc/blackroad/releases?per_page=3");
    const releaseCards=(releases||[]).map(r=>`<div style="background:#0a0a0a;border:1px solid #1a1a1a;border-radius:12px;padding:18px 20px;margin-bottom:10px"><div style="font-size:11px;color:#FF1D6C;font-weight:600;margin-bottom:4px">${r.tag_name}</div><div style="font-size:14px;color:#fff;font-weight:500;margin-bottom:6px">${r.name}</div><div style="font-size:12px;color:#555">${r.published_at?.slice(0,10)}</div></div>`).join("");
    const postCards=POSTS.map(post=>`<article style="background:#0a0a0a;border:1px solid #1a1a1a;border-radius:14px;padding:24px;margin-bottom:16px"><div style="display:flex;gap:8px;flex-wrap:wrap;margin-bottom:10px">${post.tags.map(t=>`<span style="font-size:10px;font-weight:600;letter-spacing:.08em;text-transform:uppercase;color:#9C27B0;border:1px solid rgba(156,39,176,.3);border-radius:8px;padding:2px 8px">${t}</span>`).join("")}</div><h2 style="font-size:16px;font-weight:700;color:#fff;margin-bottom:8px;line-height:1.4">${post.title}</h2><p style="font-size:13px;color:#666;line-height:1.6">${post.desc}</p><div style="margin-top:12px;font-size:11px;color:#333">${post.date}</div></article>`).join("");
    return new Response(`<!DOCTYPE html><html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Blog — BlackRoad OS</title><style>*{box-sizing:border-box;margin:0;padding:0}body{background:#000;color:#fff;font-family:-apple-system,sans-serif}.gbar{height:3px;background:linear-gradient(135deg,#F5A623,#FF1D6C,#9C27B0,#2979FF)}.header{padding:40px;border-bottom:1px solid #1a1a1a}.title{font-size:42px;font-weight:700;background:linear-gradient(135deg,#F5A623,#FF1D6C,#9C27B0,#2979FF);-webkit-background-clip:text;-webkit-text-fill-color:transparent;background-clip:text}.layout{display:grid;grid-template-columns:1fr 300px;gap:40px;padding:40px;max-width:1100px}.section-title{font-size:11px;font-weight:600;letter-spacing:.12em;text-transform:uppercase;color:#555;margin-bottom:14px;padding-bottom:8px;border-bottom:1px solid #1a1a1a}@media(max-width:800px){.layout{grid-template-columns:1fr;padding:24px}}</style></head><body>
<div class="gbar"></div>
<div class="header"><div style="font-size:11px;font-weight:600;letter-spacing:.15em;text-transform:uppercase;color:#555;margin-bottom:12px">BlackRoad OS · Blog</div><h1 class="title">Blog</h1><p style="color:#555;font-size:15px;margin-top:8px">Architecture, agents, and AI engineering at BlackRoad scale</p></div>
<div class="layout"><div><div class="section-title">Latest Posts</div>${postCards}</div>
<div><div class="section-title">Latest Releases</div>${releaseCards||"<p style='font-size:12px;color:#555'>No releases yet</p>"}</div>
</div></body></html>`,{headers:{"Content-Type":"text/html;charset=utf-8","Cache-Control":"public,max-age=300"}});
  }
};
