export default {
  async fetch(req, env) {
    const url = new URL(req.url);
    if (url.pathname === '/health') return Response.json({ ok: true, worker: 'store-blackroadio' });
    return new Response(`<!DOCTYPE html><html><head><title>🛒 Store — BlackRoad OS</title><meta charset=utf-8><meta name=viewport content="width=device-width,initial-scale=1"><style>*{margin:0;padding:0;box-sizing:border-box}body{background:#000;color:#fff;font-family:-apple-system,BlinkMacSystemFont,"SF Pro Display",sans-serif;min-height:100vh}header{background:linear-gradient(135deg,#F5A623 0%,#FF1D6C 38.2%,#9C27B0 61.8%,#2979FF 100%);padding:60px 40px;text-align:center}header h1{font-size:3rem;font-weight:800;letter-spacing:-2px}header p{opacity:.85;margin-top:12px;font-size:1.1rem}.grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(280px,1fr));gap:20px;padding:40px;max-width:1200px;margin:0 auto}.card{background:#0a0a0a;border:1px solid #1a1a1a;border-radius:12px;padding:24px;transition:.2s}.card:hover{border-color:#FF1D6C;transform:translateY(-2px)}.card h3{font-size:1.1rem;margin-bottom:8px}.card p{font-size:.85rem;opacity:.6;line-height:1.5}.tag{display:inline-block;background:#111;border:1px solid #333;border-radius:20px;padding:4px 12px;font-size:.75rem;margin-top:12px;color:#FF1D6C}footer{text-align:center;padding:40px;opacity:.4;font-size:.8rem}</style></head><body><header><h1>🛒 Store</h1><p>BlackRoad marketplace for skills, agents, and integrations</p></header><div class="grid"><div class=card><h3>Skills Marketplace</h3><p>Buy and sell agent skills with revenue share</p><span class=tag>beta</span></div>
   <div class=card><h3>Agent Blueprints</h3><p>Pre-built agent configurations for common use cases</p><span class=tag>live</span></div>
   <div class=card><h3>Integration Packs</h3><p>Platform-specific integration bundles</p><span class=tag>active</span></div>
   <div class=card><h3>Templates</h3><p>Full-stack project templates with br CLI</p><span class=tag>free</span></div>
   <div class=card><h3>Hardware Bundles</h3><p>Pi cluster kits with pre-installed BlackRoad OS</p><span class=tag>order</span></div>
   <div class=card><h3>Credits</h3><p>Compute credits for managed inference</p><span class=tag>buy</span></div></div><footer>© 2026 BlackRoad OS, Inc. · <a href=https://blackroad.io style=color:#FF1D6C>blackroad.io</a></footer></body></html>`, { headers: { 'content-type': 'text/html;charset=utf-8', 'cache-control': 'public,max-age=60' }});
  }
};
