function json(d){return new Response(JSON.stringify(d),{headers:{"Content-Type":"application/json","Access-Control-Allow-Origin":"*"}});}
const TOPOLOGY={nodes:[{id:"cf-edge",type:"cdn",name:"Cloudflare Edge",status:"online",workers:75},{id:"railway",type:"cloud",name:"Railway GPU",status:"online",services:14},{id:"pi-primary",type:"pi",name:"Pi Primary (192.168.4.64)",status:"online",agents:7500},{id:"pi-secondary",type:"pi",name:"Pi Secondary (192.168.4.38)",status:"online",agents:22500},{id:"do-droplet",type:"vps",name:"DO Infinity (159.65.43.12)",status:"online",role:"failover"},{id:"tunnel",type:"tunnel",name:"CF Tunnel (QUIC)",status:"active",protocol:"QUIC"}],edges:[{from:"cf-edge",to:"tunnel",label:"QUIC"},{from:"tunnel",to:"pi-primary",label:"LAN"},{from:"pi-primary",to:"pi-secondary",label:"mesh"},{from:"cf-edge",to:"railway",label:"HTTPS"},{from:"railway",to:"do-droplet",label:"failover"}]};
export default {
  async fetch(req){
    const {pathname:p}=new URL(req.url);
    if(p==="/health") return json({status:"ok"});
    if(p==="/api/topology") return json(TOPOLOGY);
    const nodeCards=TOPOLOGY.nodes.map(n=>`<div style="background:#0a0a0a;border:1px solid #1a1a1a;border-radius:12px;padding:16px 20px"><div style="font-size:13px;font-weight:600;color:#fff;margin-bottom:4px">${n.name}</div><div style="display:flex;gap:12px;margin-top:6px"><span style="font-size:11px;padding:2px 8px;border-radius:10px;background:rgba(74,222,128,.1);color:#4ade80;border:1px solid rgba(74,222,128,.2)">${n.status}</span><span style="font-size:11px;color:#555">${n.type}</span></div>${n.agents?`<div style="font-size:12px;color:#9C27B0;margin-top:6px">${n.agents.toLocaleString()} agents</div>`:""}${n.workers?`<div style="font-size:12px;color:#2979FF;margin-top:6px">${n.workers} workers</div>`:""}${n.services?`<div style="font-size:12px;color:#FF1D6C;margin-top:6px">${n.services} services</div>`:""}${n.role?`<div style="font-size:11px;color:#555;margin-top:4px">${n.role}</div>`:""}</div>`).join("");
    return new Response(`<!DOCTYPE html><html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Network — BlackRoad OS</title><style>*{box-sizing:border-box;margin:0;padding:0}body{background:#000;color:#fff;font-family:-apple-system,sans-serif}.gbar{height:3px;background:linear-gradient(135deg,#F5A623,#FF1D6C,#9C27B0,#2979FF)}.header{padding:40px;border-bottom:1px solid #1a1a1a}.title{font-size:42px;font-weight:700;background:linear-gradient(135deg,#F5A623,#FF1D6C,#9C27B0,#2979FF);-webkit-background-clip:text;-webkit-text-fill-color:transparent;background-clip:text}.content{padding:40px;max-width:1000px}.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:14px}@media(max-width:700px){.grid{grid-template-columns:1fr}}</style></head><body>
<div class="gbar"></div>
<div class="header"><div style="font-size:11px;font-weight:600;letter-spacing:.15em;text-transform:uppercase;color:#555;margin-bottom:12px">BlackRoad OS · Infrastructure</div><h1 class="title">Network</h1><p style="color:#555;font-size:15px;margin-top:8px">CF Edge → Pi Fleet → Railway GPU · 30,000 agents online</p></div>
<div class="content"><div style="font-size:11px;font-weight:600;letter-spacing:.12em;text-transform:uppercase;color:#555;margin-bottom:14px;padding-bottom:8px;border-bottom:1px solid #1a1a1a">Network Topology (${TOPOLOGY.nodes.length} nodes)</div>
<div class="grid">${nodeCards}</div>
<div style="margin-top:32px;font-size:11px;font-weight:600;letter-spacing:.12em;text-transform:uppercase;color:#555;margin-bottom:14px;padding-bottom:8px;border-bottom:1px solid #1a1a1a">Connections</div>
${TOPOLOGY.edges.map(e=>`<div style="display:flex;gap:10px;padding:8px 0;border-bottom:1px solid #080808;font-size:12px"><span style="color:#2979FF;font-family:'SF Mono',monospace">${e.from}</span><span style="color:#555">→</span><span style="color:#FF1D6C;font-family:'SF Mono',monospace">${e.to}</span><span style="color:#555;margin-left:auto">${e.label}</span></div>`).join("")}
</div></body></html>`,{headers:{"Content-Type":"text/html;charset=utf-8","Cache-Control":"public,max-age=60"}});
  }
};
