function json(d){return new Response(JSON.stringify(d),{headers:{"Content-Type":"application/json","Access-Control-Allow-Origin":"*"}});}
export default {
  async fetch(req){
    const {pathname:p}=new URL(req.url);
    if(p==="/health") return json({status:"ok",name:"hardware"});
    return new Response(`<!DOCTYPE html><html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Hardware — BlackRoad OS</title><style>*{box-sizing:border-box;margin:0;padding:0}body{background:#000;color:#fff;font-family:-apple-system,sans-serif}.gbar{height:3px;background:linear-gradient(135deg,#F5A623,#FF1D6C,#9C27B0,#2979FF)}.header{padding:40px;border-bottom:1px solid #1a1a1a}.eyebrow{font-size:11px;font-weight:600;letter-spacing:.15em;text-transform:uppercase;color:#555;margin-bottom:12px}.title{font-size:clamp(28px,4vw,52px);font-weight:700;background:linear-gradient(135deg,#F5A623,#FF1D6C,#9C27B0,#2979FF);-webkit-background-clip:text;-webkit-text-fill-color:transparent;background-clip:text}.content{padding:40px;max-width:900px}.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:14px}.card{background:#0a0a0a;border:1px solid #1a1a1a;border-radius:12px;padding:18px 20px}.card-name{font-size:14px;font-weight:600;color:#FF1D6C;margin-bottom:6px}.card-desc{font-size:12px;color:#666;line-height:1.5}.ts{font-size:11px;color:#333;margin-top:32px;padding-top:12px;border-top:1px solid #1a1a1a}@media(max-width:700px){.grid{grid-template-columns:1fr 1fr}}@media(max-width:480px){.grid{grid-template-columns:1fr}}</style></head><body>
<div class="gbar"></div>
<div class="header"><div class="eyebrow">BlackRoad OS · IoT & Hardware</div><h1 class="title">Hardware</h1><p style="color:#555;font-size:15px;margin-top:8px">Raspberry Pi fleet, IoT sensors, hardware management</p></div>
<div class="content"><div class="grid"><div class="card"><div class="card-name">Pi Primary</div><div class="card-desc">192.168.4.64 · 7,500 agents · Cloudflared tunnel</div></div><div class="card"><div class="card-name">Pi Secondary</div><div class="card-desc">192.168.4.38 · 22,500 agents · AI accelerator</div></div><div class="card"><div class="card-name">DO Droplet</div><div class="card-desc">159.65.43.12 · Failover · 1GB RAM</div></div><div class="card"><div class="card-name">iPhone Koder</div><div class="card-desc">192.168.4.68:8080 · Mobile dev</div></div><div class="card"><div class="card-name">BR Pi CLI</div><div class="card-desc">br pi status · br pi deploy · br pi ssh</div></div><div class="card"><div class="card-name">Fleet Deploy</div><div class="card-desc">Zero-downtime rolling deployments to Pi fleet</div></div></div><div class="ts">Updated ${new Date().toISOString()}</div></div>
</body></html>`,{headers:{"Content-Type":"text/html;charset=utf-8","Cache-Control":"public,max-age=300"}});
  }
};
